In [36]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.datasets import make_regression
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split

In [2]:
data='/content/Tray164.csv'
df = pd.read_csv(data)
df.head()

Elbow_Left_X  Elbow_Left_Y  Mouth_Back_Left_X  Mouth_Back_Left_Y  \
0    104.139679    325.075928                NaN                NaN   
1    115.922638    327.997528                NaN                NaN   
2    117.071671    324.612488                NaN                NaN   
3    136.452759    315.592346                NaN                NaN   
4           NaN           NaN                NaN                NaN   

   Head_Mid_Top_X  Head_Mid_Top_Y  Mouth_Back_Right_X  Mouth_Back_Right_Y  \
0      128.574951       57.189270                 NaN                 NaN   
1      124.315826       56.024841                 NaN                 NaN   
2      125.189728       56.183884                 NaN                 NaN   
3      120.604019       55.201263                 NaN                 NaN   
4       96.864517       52.384766                 NaN                 NaN   

   Knee_Left_X  Knee_Left_Y  ...  AC135  AC136  AC137  AC138  AC139  AC140  \
0   184.139526   332.459229  ...      0      0      0      0      0      0   
1   176.399780   340.395050  ...      0      0      0      0      0      0   
2   177.687714   344.317566  ...      0      0      0      0      0      0   
3   184.897964   336.024109  ...      0      0      0      0      0      0   
4   144.741913   307.945831  ...      0      0      0      0      0      0   

   AC141  AC142  AC143  AC144  
0      0      0      0      0  
1      0      0      0      0  
2      0      0      0      0  
3      0      0      0      0  
4      0      0      0      0  

[5 rows x 193 columns]

In [3]:
df=df.fillna(value=-1)

In [4]:
df.isnull().sum().sum()

0

In [5]:
Classes=[]
for i in range(48,193):
  Classes.append(df.columns[i])

Classes

['AC0',
 'AC1',
 'AC2',
 'AC3',
 'AC4',
 'AC5',
 'AC6',
 'AC7',
 'AC8',
 'AC9',
 'AC10',
 'AC11',
 'AC12',
 'AC13',
 'AC14',
 'AC15',
 'AC16',
 'AC17',
 'AC18',
 'AC19',
 'AC20',
 'AC21',
 'AC22',
 'AC23',
 'AC24',
 'AC25',
 'AC26',
 'AC27',
 'AC28',
 'AC29',
 'AC30',
 'AC31',
 'AC32',
 'AC33',
 'AC34',
 'AC35',
 'AC36',
 'AC37',
 'AC38',
 'AC39',
 'AC40',
 'AC41',
 'AC42',
 'AC43',
 'AC44',
 'AC45',
 'AC46',
 'AC47',
 'AC48',
 'AC49',
 'AC50',
 'AC51',
 'AC52',
 'AC53',
 'AC54',
 'AC55',
 'AC56',
 'AC57',
 'AC58',
 'AC59',
 'AC60',
 'AC61',
 'AC62',
 'AC63',
 'AC64',
 'AC65',
 'AC66',
 'AC67',
 'AC68',
 'AC69',
 'AC70',
 'AC71',
 'AC72',
 'AC73',
 'AC74',
 'AC75',
 'AC76',
 'AC77',
 'AC78',
 'AC79',
 'AC80',
 'AC81',
 'AC82',
 'AC83',
 'AC84',
 'AC85',
 'AC86',
 'AC87',
 'AC88',
 'AC89',
 'AC90',
 'AC91',
 'AC92',
 'AC93',
 'AC94',
 'AC95',
 'AC96',
 'AC97',
 'AC98',
 'AC99',
 'AC100',
 'AC101',
 'AC102',
 'AC103',
 'AC104',
 'AC105',
 'AC106',
 'AC107',
 'AC108',
 'AC109',
 'AC110',


In [6]:
X=df.iloc[:,:-147]
y=df[Classes]

In [7]:
X.head()

Elbow_Left_X  Elbow_Left_Y  Mouth_Back_Left_X  Mouth_Back_Left_Y  \
0    104.139679    325.075928               -1.0               -1.0   
1    115.922638    327.997528               -1.0               -1.0   
2    117.071671    324.612488               -1.0               -1.0   
3    136.452759    315.592346               -1.0               -1.0   
4     -1.000000     -1.000000               -1.0               -1.0   

   Head_Mid_Top_X  Head_Mid_Top_Y  Mouth_Back_Right_X  Mouth_Back_Right_Y  \
0      128.574951       57.189270                -1.0                -1.0   
1      124.315826       56.024841                -1.0                -1.0   
2      125.189728       56.183884                -1.0                -1.0   
3      120.604019       55.201263                -1.0                -1.0   
4       96.864517       52.384766                -1.0                -1.0   

   Knee_Left_X  Knee_Left_Y  ...  Tail_End_Back_X  Tail_End_Back_Y  \
0   184.139526   332.459229  ...       364.553619       148.925858   
1   176.399780   340.395050  ...       360.222412       148.113617   
2   177.687714   344.317566  ...        -1.000000        -1.000000   
3   184.897964   336.024109  ...        -1.000000        -1.000000   
4   144.741913   307.945831  ...        -1.000000        -1.000000   

   Ankle_Left _X  Ankle_Left _Y  Torso_Mid_Back_X  Torso_Mid_Back_Y  \
0       -1.00000      -1.000000              -1.0              -1.0   
1       -1.00000      -1.000000              -1.0              -1.0   
2       -1.00000      -1.000000              -1.0              -1.0   
3       -1.00000      -1.000000              -1.0              -1.0   
4      141.38681     332.439697              -1.0              -1.0   

   Wrist_Left_X  Wrist_Left_Y  Hip_Right_X  Hip_Right_Y  
0     -1.000000     -1.000000   244.634369   124.360077  
1     -1.000000     -1.000000   251.890045   128.287766  
2    116.180374    352.261505   265.547150   132.841141  
3    131.841553    347.619141   284.149994   139.937271  
4    104.409271    328.530914    -1.000000    -1.000000  

[5 rows x 46 columns]

In [8]:
y.head()

AC0  AC1  AC2  AC3  AC4  AC5  AC6  AC7  AC8  AC9  ...  AC135  AC136  AC137  \
0    0    0    0    0    0    0    0    0    0    0  ...      0      0      0   
1    0    0    0    0    0    0    0    0    0    0  ...      0      0      0   
2    0    0    0    0    0    0    0    0    0    0  ...      0      0      0   
3    0    0    0    0    0    0    0    0    0    0  ...      0      0      0   
4    0    0    0    0    0    0    0    0    0    0  ...      0      0      0   

   AC138  AC139  AC140  AC141  AC142  AC143  AC144  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 145 columns]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
X_train.shape,X_test.shape

((6248, 46), (1562, 46))

In [11]:
y_train.shape,y_test.shape

((6248, 145), (1562, 145))

# Multi-layerPerceptronClassifier

In [18]:
Model = MLPClassifier(random_state=0,activation='relu',max_iter=1000).fit(X_train, y_train)

In [19]:
proba=Model.predict_proba(X_test)
binpre=Model.predict(X_test)

In [20]:
proba

array([[1.10697163e-105, 1.71083016e-067, 3.14039943e-029, ...,
        4.09538743e-088, 8.53348154e-101, 9.99027113e-081],
       [4.24967226e-066, 3.09774856e-032, 2.95173946e-022, ...,
        2.50347939e-076, 3.54711642e-051, 4.97332716e-037],
       [4.32159130e-089, 9.68703669e-082, 4.61910457e-016, ...,
        6.81792127e-091, 7.94810448e-123, 2.11978781e-109],
       ...,
       [3.36738597e-098, 3.49818918e-074, 1.46592836e-024, ...,
        1.39157814e-072, 9.01807552e-204, 1.56666287e-084],
       [9.77401205e-139, 8.29185757e-139, 2.92769426e-039, ...,
        4.23617108e-114, 4.16498765e-208, 2.47238445e-083],
       [2.33992335e-012, 3.12929024e-008, 2.14790945e-006, ...,
        5.63541215e-011, 3.65003976e-009, 1.26215629e-016]])

In [21]:
binpre

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [22]:
print('Train Accuracy = {0}%'.format(np.round(Model.score(X_train,y_train)*100,2)))

print('Test Accuracy = {0}%'.format(np.round(Model.score(X_test,y_test)*100,2)))

Train Accuracy = 75.21%
Test Accuracy = 62.93%


In [27]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [28]:
data='/content/drive/MyDrive/COCOHorseSleapPose/Updata.csv'
df2 = pd.read_csv(data)
df2=df2.fillna(value=-1)
df2.head()

Elbow_Left_X  Elbow_Left_Y  Mouth_Back_Left_X  Mouth_Back_Left_Y  \
0          -1.0          -1.0               -1.0               -1.0   
1          -1.0          -1.0               -1.0               -1.0   
2          -1.0          -1.0               -1.0               -1.0   
3          -1.0          -1.0               -1.0               -1.0   
4          -1.0          -1.0               -1.0               -1.0   

   Head_Mid_Top_X  Head_Mid_Top_Y  Mouth_Back_Right_X  Mouth_Back_Right_Y  \
0       -1.000000       -1.000000                -1.0                -1.0   
1       -1.000000       -1.000000                -1.0                -1.0   
2       -1.000000       -1.000000                -1.0                -1.0   
3       -1.000000       -1.000000                -1.0                -1.0   
4      557.099548      105.430542                -1.0                -1.0   

   Knee_Left_X  Knee_Left_Y  ...  AC135  AC136  AC137  AC138  AC139  AC140  \
0   552.346558   197.129211  ...      0      0      0      0      0      0   
1   552.168823   197.092896  ...      0      0      0      0      0      0   
2    -1.000000    -1.000000  ...      0      0      0      0      0      0   
3    -1.000000    -1.000000  ...      0      0      0      0      0      0   
4    -1.000000    -1.000000  ...      0      0      0      0      0      0   

   AC141  AC142  AC143  AC144  
0      0      0      0      0  
1      0      0      0      0  
2      0      0      0      0  
3      0      0      0      0  
4      0      0      0      0  

[5 rows x 193 columns]

In [29]:
df2.isnull().sum().sum()

0

In [30]:
X_test2=df2.iloc[:,:-147]
X_test2.head()

Elbow_Left_X  Elbow_Left_Y  Mouth_Back_Left_X  Mouth_Back_Left_Y  \
0          -1.0          -1.0               -1.0               -1.0   
1          -1.0          -1.0               -1.0               -1.0   
2          -1.0          -1.0               -1.0               -1.0   
3          -1.0          -1.0               -1.0               -1.0   
4          -1.0          -1.0               -1.0               -1.0   

   Head_Mid_Top_X  Head_Mid_Top_Y  Mouth_Back_Right_X  Mouth_Back_Right_Y  \
0       -1.000000       -1.000000                -1.0                -1.0   
1       -1.000000       -1.000000                -1.0                -1.0   
2       -1.000000       -1.000000                -1.0                -1.0   
3       -1.000000       -1.000000                -1.0                -1.0   
4      557.099548      105.430542                -1.0                -1.0   

   Knee_Left_X  Knee_Left_Y  ...  Tail_End_Back_X  Tail_End_Back_Y  \
0   552.346558   197.129211  ...             -1.0             -1.0   
1   552.168823   197.092896  ...             -1.0             -1.0   
2    -1.000000    -1.000000  ...             -1.0             -1.0   
3    -1.000000    -1.000000  ...             -1.0             -1.0   
4    -1.000000    -1.000000  ...             -1.0             -1.0   

   Ankle_Left _X  Ankle_Left _Y  Torso_Mid_Back_X  Torso_Mid_Back_Y  \
0     564.281006     221.618042        405.100739         90.036453   
1     560.907593     220.193634        405.126221         89.464828   
2     557.471008     220.740875        403.890869         90.095901   
3     556.078735     219.874069        400.810394         91.881516   
4      -1.000000      -1.000000        396.623108         91.853989   

   Wrist_Left_X  Wrist_Left_Y  Hip_Right_X  Hip_Right_Y  
0          -1.0          -1.0   413.137329    88.146378  
1          -1.0          -1.0   409.586212    87.144913  
2          -1.0          -1.0   412.404358    88.234253  
3          -1.0          -1.0   411.996368    87.791702  
4          -1.0          -1.0   408.733063    88.228653  

[5 rows x 46 columns]

In [31]:
y_test2=df2[Classes]
y_test2.head()

AC0  AC1  AC2  AC3  AC4  AC5  AC6  AC7  AC8  AC9  ...  AC135  AC136  AC137  \
0    0    0    0    0    0    0    0    0    0    0  ...      0      0      0   
1    0    0    0    0    0    0    0    0    0    0  ...      0      0      0   
2    0    0    0    0    0    0    0    0    0    0  ...      0      0      0   
3    0    0    0    0    0    0    0    0    0    0  ...      0      0      0   
4    0    0    0    0    0    0    0    0    0    0  ...      0      0      0   

   AC138  AC139  AC140  AC141  AC142  AC143  AC144  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 145 columns]

In [32]:
proba2=Model.predict_proba(X_test2)
binpre2=Model.predict(X_test2)

In [35]:
accuracy = accuracy_score(y_test2, binpre2)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 6.75%


In [34]:
print('Test Accuracy = {0}%'.format(np.round(Model.score(X_test2,y_test2)*100,2)))

Test Accuracy = 6.75%


# MultiOutput GradientBoostingRegressor

In [ ]:
# Time 23m

In [37]:
GBModel=MultiOutputRegressor(GradientBoostingRegressor(random_state=0,n_estimators=1000,learning_rate=0.03,max_depth=3))
GBModel.fit(X_train, y_train)

MultiOutputRegressor(estimator=GradientBoostingRegressor(learning_rate=0.03,
                                                         n_estimators=1000,
                                                         random_state=0))

In [38]:
pre=GBModel.predict(X_test)

In [39]:
pre

array([[ 0.        ,  0.        , -0.0059503 , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -0.00898546, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -0.00769096, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        , -0.04106229, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.00200174, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.01563196, ...,  0.        ,
         0.        ,  0.        ]])

In [40]:
print('Train Accuracy = {0}%'.format(np.round(GBModel.score(X_train,y_train)*100,2)))

print('Test Accuracy = {0}%'.format(np.round(GBModel.score(X_test,y_test)*100,2)))

Train Accuracy = 98.92%
Test Accuracy = 92.11%


In [41]:
pre2=GBModel.predict(X_test2)

In [42]:
print('Test Accuracy = {0}%'.format(np.round(GBModel.score(X_test2,y_test2)*100,2)))

Test Accuracy = 78.79%
